### ISSUE TITLE
Training job failed when executing train.py

### ISSUE THREAD

**Issue by mbrhd** [aws-samples/amazon-sagemaker-gluonts-entrypoint#2]
Hi,
Thanks for this great sample code.

I followed all the instructions. But the training job fails. 

I'm getting the following message:
`AlgorithmError: ExecuteUserScriptError: Command "/usr/local/bin/python3.6 train.py --algo gluonts.model.deepar.DeepAREstimator --cardinality [151] --cell_type gru --distr_output.__class__ gluonts.distribution.gaussian.GaussianOutput --num_cells 46 --num_layers 4 --num_samples 1000 --plot_transparent 0 --prediction_length 30 --trainer.__class__ gluonts.trainer.Trainer --trainer.epochs 200 --trainer.learning_rate 0.0005490034989544101 --use_feat_static_cat True"`

The Traceback in cloud watch provides me with this error

```
Traceback (most recent call last):
  File "train.py", line 197, in <module>
    train(args, smepu.argparse.to_kwargs(train_args))
  File "/usr/local/lib/python3.6/site-packages/smepu/argparse.py", line 83, in to_kwargs
    args_round_2 = _round_2(args_round_1)  # Custom class in IR
  File "/usr/local/lib/python3.6/site-packages/smepu/argparse.py", line 211, in _round_2
    desered = {k: decode(v.klass_dict) for k, v in ir.items()}
  File "/usr/local/lib/python3.6/site-packages/smepu/argparse.py", line 211, in <dictcomp>
    desered = {k: decode(v.klass_dict) for k, v in ir.items()}
  File "/usr/local/lib/python3.6/site-packages/smepu/_gluonts_core_serde.py", line 49, in decode
    return cls(*args, **kwargs)  # type: ignore

TypeError: 'NoneType' object is not callable
```

I'm using latest gluonts release 0.7.6

**Comment by verdimrc** [comment]
Hi @bidHimArm, gluonts-0.7.x changes the class names of distribution and trainer. As you can see from the [DeepAREstimator signature](https://ts.gluon.ai/api/gluonts/gluonts.model.deepar.html), the classes have become `gluonts.mx.distribution.GaussianOutput` and `gluonts.mx.trainer._base.Trainer`.

The `None` error you seen was due to the script failed to find the old class names in your gluonts-0.7.x environment.

Btw, it's recommended to run this script with gluonts 0.5.x and mxnet-1.6.0. There're reports from users who've ran on gluonts-0.6.x and mxnet-1.7.0, but not with mxnet-1.8.0.
